FROM ros1-bridge-base-image:latest
RUN   cd /ros-humble-ros1-bridge/src; \
      git clone https://github.com/usdot-fhwa-stol/ros1_bridge/ -b develop-humble-buildable; \
      cd ..;                    \
      source /opt/ros/humble/setup.bash; \
      source /home/carma/.base-image/ros1_msgs_ws/install/local_setup.bash; \
      source /home/carma/.base-image/ros2_msgs_ws/install/local_setup.bash; \
      MEMG=$(printf "%.0f" $(free -g | awk '/^Mem:/{print $2}'));                 \
      NPROC=$(nproc);  MIN=$((MEMG<NPROC ? MEMG : NPROC));                        \
      echo "Please wait...  running $MIN concurrent jobs to build ros1_bridge";   \
      time MAKEFLAGS="-j $MIN" colcon build --event-handlers console_direct+      \
      --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-select ros1_bridge --cmake-force-configure
      
###########################
# 8.) Clean up
###########################
RUN apt-get -y clean all; apt-get -y update

###########################
# 9.) Pack all ROS1 dependent libraries
###########################
# fix ARM64 pkgconfig path issue -- Fix provided by ambrosekwok
RUN if [[ $(uname -m) = "arm64" || $(uname -m) = "aarch64" ]]; then                    \
      cp /usr/lib/x86_64-linux-gnu/pkgconfig/* /usr/lib/aarch64-linux-gnu/pkgconfig/;  \
    fi

RUN ROS1_LIBS="libxmlrpcpp.so";                                                 \
     ROS1_LIBS="$ROS1_LIBS librostime.so";                                      \
     ROS1_LIBS="$ROS1_LIBS libroscpp.so";                                       \
     ROS1_LIBS="$ROS1_LIBS libroscpp_serialization.so";                         \
     ROS1_LIBS="$ROS1_LIBS librosconsole.so";                                   \
     ROS1_LIBS="$ROS1_LIBS librosconsole_log4cxx.so";                           \
     ROS1_LIBS="$ROS1_LIBS librosconsole_backend_interface.so";                 \
     ROS1_LIBS="$ROS1_LIBS liblog4cxx.so";                                      \
     ROS1_LIBS="$ROS1_LIBS libcpp_common.so";                                   \
     ROS1_LIBS="$ROS1_LIBS libb64.so";                                          \
     ROS1_LIBS="$ROS1_LIBS libaprutil-1.so";                                    \
     ROS1_LIBS="$ROS1_LIBS libapr-1.so";                                        \
     ROS1_LIBS="$ROS1_LIBS libactionlib.so.1d";                                 \
     cd /ros-humble-ros1-bridge/install/ros1_bridge/lib;                        \
     for soFile in $ROS1_LIBS; do                                               \
       soFilePath=$(ldd libros1_bridge.so | grep $soFile | awk '{print $3;}');  \
       cp $soFilePath ./;                                                       \
     done

###########################
# 10.0) Metadata
###########################
ARG VERSION="NULL"
ARG VCS_REF="NULL"
ARG BUILD_DATE="NULL"

LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.name="carma-msgs" \
      org.label-schema.description="carma msgs bridge for the CARMA Platform" \
      org.label-schema.vendor="Leidos" \
      org.label-schema.version=${VERSION} \
      org.label-schema.url="https://highways.dot.gov/research/research-programs/CARMA" \
      org.label-schema.vcs-url="https://github.com/usdot-fhwa-stol/carma-msgs" \
      org.label-schema.vcs-ref=${VCS_REF} \
      org.label-schema.build-date=${BUILD_DATE}