# PlanManeuvers.srv
#
# Service used to request a maneuver plan from a plugin
#
#

#request

# Maneuvers planned prior to the current planning request.
# These maneuvers must not be modified by this process
cav_msgs/ManeuverPlan prior_plan
---

#response

# The returned maneuver plan, must be a strict superset of prior plan
cav_msgs/ManeuverPlan new_plan