# SetLights.srv

# Request - set the light values

# Used by lighbar driver
# This should contain the desired state of all lights, not just the ones
# intended to be changed
carma_driver_msgs/LightBarStatus set_state

---

# Response - no Response