#
# AttachmentRadius.msg
#
# Modified J2735 2016 message format, adjusted to use base SI units (m,s, etc) in most case.
#
# Parsed description of AttachmentRadius from the SAE J2735 2016 specification.
# For further usage details consult the specification. See note on SI units above.
#
# AttachmentRadius in meters in range (0..20)
float32 attachment_radius

float32 ATTACHMENT_RADIUS_MIN= 0.0
float32 ATTACHMENT_RADIUS_MAX = 20.0