#
# ComputePlanCost.srv
# 
# Provided by the cost plugin node. Returns a final cost of a given maneuver plan.
#
# @author Fang Zhou
# @version 0.1
#

# Request
carma_planning_msgs/ManeuverPlan maneuver_plan

---
# Response
float64 plan_cost