#
# GetEmergencyRoute.srv
# 
# Provided by the EmergencyResponseVehicle node. Call the service to receive the name of 
#   the node's current emergency route, if it was successfully loaded. 
#   Responds with success boolean and name of loaded route. 
#
# @author Alex Frye
# @version 0.1
#

# Request - No arguments

---
# Response

# Success boolean
bool is_successful

# Name of route selected
string route_name
