#
# SetActiveRoute.srv
# 
# Service provided by RouteManager node. Sets a route with the 
# specified id as the active route.
#
# @author Michael McConnell
# @version 0.1
#

# Request
# Enumeration values for the method being used to provide the route destination points
uint8 choice

uint8 ROUTE_ID=0
uint8 DESTINATION_POINTS_ARRAY=1

# The id of the route to select
string route_id

# The array of destination points to be used for route generation 
carma_v2x_msgs/Position3D[] destination_points

---
# Response
# An enumeration representing a service execution error as defined in the route design document.
uint8 error_status

# enumeration values for errorStatus:
uint8 NO_ERROR=0
uint8 NO_ROUTE=1
uint8 ALREADY_FOLLOWING_ROUTE=2
uint8 ROUTE_FILE_ERROR=3
uint8 ROUTING_FAILURE=4
uint8 TRANSFORM_ERROR=5
#					<other values reserved for future expansion>
