name: Docker build

on:
  push:
    branches-ignore:
      - develop
      - master
      - "release/*"
  pull_request:
      types: [opened, synchronize, reopened]
      
jobs:
  docker:
    uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@main
