name: Build and upload .deb files

on:
  push:
    branches:
      - "debian-packaging"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PACKAGES: can_msgs carma_cmake_common carma_debug_msgs carma_debug_ros2_msgs carma_driver_msgs carma_localization_msgs carma_msgs carma_perception_msgs carma_planning_msgs carma_v2x_msgs cav_msgs cav_srvs j2735_msgs j2735_v2x_msgs

jobs:
  apt-repo:
    runs-on: ubuntu-latest
    container:
      image: usdotfhwastoldev/autoware.ai:develop
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add stol apt repo
        run: |
          echo "deb [trusted=yes] https://s3.amazonaws.com/${{ secrets.AWS_BUCKET_NAME }} develop main" > /etc/apt/sources.list.d/carma.list
      - name: Install dependencies
        run: |
          apt update
          apt -y install debhelper devscripts equivs
          gem install deb-s3
      - name: Build and upload .deb files
        run: |
          # Avoid fatal git warning
          git config --global --add safe.directory '*'

          for PACKAGE in $(find $GITHUB_WORKSPACE -type d -name debian | sed 's/debian//'); do
            git -C $GITHUB_WORKSPACE clean -dfx
            cd $PACKAGE
            mk-build-deps
            dpkg -i *.deb || true
            apt-get -f -y install
            debuild -us -uc -j -b
            deb-s3 upload --codename develop --bucket ${{ secrets.AWS_BUCKET_NAME }} ../*.deb
          done
