name: Build and upload .deb files

on:
  push:
    branches:
      - "debian-packaging"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  apt-repo:
    runs-on: ubuntu-latest
    container:
      image: usdotfhwastoldev/autoware.ai:develop
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add STOL apt repository
        uses: usdot-fhwa-stol/actions/add-stol-apt-repository@main
        with:
          codename: "develop"
      - name: Install deb-s3 and tools
        uses: usdot-fhwa-stol/actions/setup-deb-s3@main
        with:
          bloom: "true"
          mk-build-deps: "true"
      - name: Build and upload .deb files
        run: |
          # Avoid fatal git warning
          git config --global --add safe.directory '*'

          for PACKAGE in $(find $GITHUB_WORKSPACE -type d -name debian | sed 's/debian//'); do
            git -C $GITHUB_WORKSPACE clean -dfx
            cd $PACKAGE
            mk-build-deps
            dpkg -i *.deb || true
            apt-get update
            apt-get -f -y install
            dch --local .$(date +%Y%m%d).git$(git rev-list --count HEAD).$(git rev-parse --short HEAD). "CI build"
            debuild -us -uc -j -b
            deb-s3 upload --codename develop --bucket ${{ secrets.AWS_BUCKET_NAME }} ../*.deb
          done
